spring.application.name=notification-service
server.port=8084

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.notification_service.*
spring.kafka.consumer.properties[spring.json.use.type.headers]=true

spring.kafka.consumer.properties[spring.json.type.mapping]=com.example.payment_service.dto.PaymentEvent:com.example.notification_service.dto.PaymentEvent,com.example.delivery_service.dto.DeliveryCreatedEvent:com.example.notification_service.dto.DeliveryCreatedEvent,com.example.orderservice.dto.OrderCreatedEvent:com.example.notification_service.dto.OrderCreatedEvent